config = {
    "CLEAN_TMP":False,
    "SKIP_DOWNLOADS":True,
    "SKIP_CROPPING":True,
    "AUTO_INSTALL_REQUIREMENTS":True,
    "OUTPUT_NETWORK":"network.xml",
    "OUTPUT_SCHEDULE":"schedule.xml",
    "OUTPUT_VEHICLES":"vehicles.xml",
    "OSM":{
        "FILE":".tmp/portugal.osm.pbf",
        "URL":"https://download.geofabrik.de/europe/portugal-latest.osm.pbf",
        "CROP_RELATION":5396817,
        "CROP_FILE":".tmp/amp.osm.pbf",
    },  
    "CRS":"EPSG:3763",
    "PUBLIC_TRANSPORT":{
        "merged":{
            "PASSENGERS_PER_VEHICLE":103,
            "LOCAL_PATH":".tmp/gtfs_merged.zip",
            "DATE":"20251214",
        }
    }
}